//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.19 at 10:40:13 PM CEST 
//


package org.w3._2005._10.markup_validator;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ValidationErrors complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ValidationErrors"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="errorcount" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="errorlist" type="{http://www.w3.org/2005/10/markup-validator}ErrorList"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 * @author radio.koza
 * @version $Id: $Id
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ValidationErrors", propOrder = {
    "errorcount",
    "errorlist"
})
public class ValidationErrors {

    /**
     *
     */
    protected int errorcount;

    /**
     *
     */
    @XmlElement(required = true)
    protected ErrorList errorlist;

    /**
     * Gets the value of the errorcount property.
     *
     * @return a int.
     */
    public int getErrorcount() {
        return errorcount;
    }

    /**
     * Sets the value of the errorcount property.
     *
     * @param value a int.
     */
    public void setErrorcount(int value) {
        this.errorcount = value;
    }

    /**
     * Gets the value of the errorlist property.
     *
     * @return a {@link org.w3._2005._10.markup_validator.ErrorList} object.
     */
    public ErrorList getErrorlist() {
        return errorlist;
    }

    /**
     * Sets the value of the errorlist property.
     *
     * @param value
     *     allowed object is
     *     {@link org.w3._2005._10.markup_validator.ErrorList}
     */
    public void setErrorlist(ErrorList value) {
        this.errorlist = value;
    }

}
