//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.19 at 08:32:17 PM CEST 
//


package org.w3._2005._10.markup_validator;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ValidationWarnings complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ValidationWarnings">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="warningcount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="warninglist" type="{http://www.w3.org/2005/10/markup-validator}WarningList"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ValidationWarnings", propOrder = {
    "warningcount",
    "warninglist"
})
public class ValidationWarnings {

    protected int warningcount;
    @XmlElement(required = true)
    protected WarningList warninglist;

    /**
     * Gets the value of the warningcount property.
     * 
     */
    public int getWarningcount() {
        return warningcount;
    }

    /**
     * Sets the value of the warningcount property.
     * 
     */
    public void setWarningcount(int value) {
        this.warningcount = value;
    }

    /**
     * Gets the value of the warninglist property.
     * 
     * @return
     *     possible object is
     *     {@link WarningList }
     *     
     */
    public WarningList getWarninglist() {
        return warninglist;
    }

    /**
     * Sets the value of the warninglist property.
     * 
     * @param value
     *     allowed object is
     *     {@link WarningList }
     *     
     */
    public void setWarninglist(WarningList value) {
        this.warninglist = value;
    }

}
