//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.19 at 10:40:20 PM CEST 
//
package org.w3._2005._07.css_validator;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Culprit complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="Culprit"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="line" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="level" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 * @author radio.koza
 * @version $Id: $Id
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Culprit", propOrder = {
    "line",
    "level",
    "message"
})
@XmlSeeAlso({
    Warning.class,
    Error.class
})
public abstract class Culprit {

    protected int line;
    protected int level;
    @XmlElement(required = true)
    protected String message;

    /**
     * Gets the value of the line property.
     *
     * @return a int.
     */
    public int getLine() {
        return line;
    }

    /**
     * Sets the value of the line property.
     *
     * @param value a int.
     */
    public void setLine(int value) {
        this.line = value;
    }

    /**
     * Gets the value of the level property.
     *
     * @return a int.
     */
    public int getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     *
     * @param value a int.
     */
    public void setLevel(int value) {
        this.level = value;
    }

    /**
     * Gets the value of the message property.
     *
     * @return a {@link java.lang.String} object.
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     *
     * @param value allowed object is {@link java.lang.String}
     */
    public void setMessage(String value) {
        this.message = value;
    }

}
