//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.19 at 10:40:20 PM CEST 
//
package org.w3._2005._07.css_validator;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ValidationWarnings complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="ValidationWarnings"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="warningcount" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="warninglist" type="{http://www.w3.org/2005/07/css-validator}WarningList" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}lang"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 * @author radio.koza
 * @version $Id: $Id
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ValidationWarnings", propOrder = {
    "warningcount",
    "warninglist"
})
public class ValidationWarnings {

    protected int warningcount;
    protected List<WarningList> warninglist;
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    protected String lang;

    /**
     * Gets the value of the warningcount property.
     *
     * @return a int.
     */
    public int getWarningcount() {
        return warningcount;
    }

    /**
     * Sets the value of the warningcount property.
     *
     * @param value a int.
     */
    public void setWarningcount(int value) {
        this.warningcount = value;
    }

    /**
     * Gets the value of the warninglist property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the warninglist property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWarninglist().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.w3._2005._07.css_validator.WarningList}
     *
     * @return a {@link java.util.List} object.
     */
    public List<WarningList> getWarninglist() {
        if (warninglist == null) {
            warninglist = new ArrayList<WarningList>();
        }
        return this.warninglist;
    }

    /**
     * Gets the value of the lang property.
     *
     * @return a {@link java.lang.String} object.
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     *
     * @param value allowed object is {@link java.lang.String}
     */
    public void setLang(String value) {
        this.lang = value;
    }

}
