//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.19 at 10:40:13 PM CEST 
//


package org.w3._2005._10.markup_validator;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.w3._2005._10.markup_validator package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Markupvalidationresponse_QNAME = new QName("http://www.w3.org/2005/10/markup-validator", "markupvalidationresponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.w3._2005._10.markup_validator
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MarkupValidationResponse }
     * 
     * @return 
     */
    public MarkupValidationResponse createMarkupValidationResponse() {
        return new MarkupValidationResponse();
    }

    /**
     * Create an instance of {@link WarningList }
     * 
     * @return 
     */
    public WarningList createWarningList() {
        return new WarningList();
    }

    /**
     * Create an instance of {@link Warning }
     * 
     * @return 
     */
    public Warning createWarning() {
        return new Warning();
    }

    /**
     * Create an instance of {@link ErrorList }
     * 
     * @return 
     */
    public ErrorList createErrorList() {
        return new ErrorList();
    }

    /**
     * Create an instance of {@link ValidationErrors }
     * 
     * @return 
     */
    public ValidationErrors createValidationErrors() {
        return new ValidationErrors();
    }

    /**
     * Create an instance of {@link ValidationWarnings }
     * 
     * @return 
     */
    public ValidationWarnings createValidationWarnings() {
        return new ValidationWarnings();
    }

    /**
     * Create an instance of {@link Error }
     * 
     * @return 
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link Debug }
     * 
     * @return 
     */
    public Debug createDebug() {
        return new Debug();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MarkupValidationResponse }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2005/10/markup-validator", name = "markupvalidationresponse")
    public JAXBElement<MarkupValidationResponse> createMarkupvalidationresponse(MarkupValidationResponse value) {
        return new JAXBElement<MarkupValidationResponse>(_Markupvalidationresponse_QNAME, MarkupValidationResponse.class, null, value);
    }

}
